#!/bin/bash

bundleDate=`date "+%y%m%d%H%M%S"`
bundle="${bundleDate}_bundle.tar.gz"
tmpBunDir='tmpBunDir'
mkdir "$tmpBunDir"
SetFile -a V "$tmpBunDir"

echo "Creating bundle..."

tar -pczf "$tmpBunDir/$bundle" --exclude "$tmpBunDir" -I "./.buninclude"

cat "./.bundirs" | while read d
do
	cp -fp "$tmpBunDir/$bundle" "$d"
done

rm -fR "$tmpBunDir"

echo "Bundle $bundleDate complete!"

exit 0