#!/bin/bash

dateName=`date "+%y%m%d%H%M%S"`

#name tarball appropriately
if [ "$1" == -s ]
then
	echo "Creating stash..."
	tarball="${dateName}_stash.tar.gz"
	saveType="Stash"
else
	echo "Creating backup..."
	tarball="${dateName}.tar.gz"
	saveType="Backup"
fi

#create hidden folder for tarball while gzipping
tmpBakDir='kbn_tmp'
mkdir "$tmpBakDir"
SetFile -a V "$tmpBakDir"

#zip files except ones specified to ignore
tar -pczf "$tmpBakDir/$tarball" --exclude "$tmpBakDir" -X "./.bakignore" "./"

#copy tarball to specified directories
cat "./.bakdirs" | while read d
do
	cp -fp "$tmpBakDir/$tarball" "$d"
done

#remove tarball from current directory
rm -fR "$tmpBakDir"

echo "$saveType $dateName complete!"

exit 0